org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.128
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties

mod_id=travelersboots
mod_name=Traveler's Boots
mod_license=MIT License
mod_version=0.0.7-1.21.1
mod_group_id=net.iggnom.travelersboots
mod_authors=IGgnom
mod_description=Run faster. Jump higher.

## Curios Properties
curios_version=9.5.1+1.21.1